import React from 'react'
import './About.css'
import watch from '../../assets/watch_img.jpg'
import story_img from '../../assets/story_img.jpg'
import bishnu from '../../assets/bishnu.jpg'


const About = () => {
  return (
    <div className='about'>
        <div className='about-left'>
        <h3>CNC Work</h3>
        <p>A CNC machine is a motorized maneuverable tool and often a motorized maneuverable platform, which are both controlled by a computer, according to specific input instructions. Instructions are delivered to a CNC machine in the form of a sequential program of machine control instructions such as G-code and M-code, and then executed. The program can be written by a person or, far more often, generated by graphical computer-aided design (CAD) or computer-aided manufacturing (CAM) software. In the case of 3D printers, the part to be printed is "sliced" before the instructions (or the program) are generated. 3D printers also use G-Code.</p>
        <img src={story_img} width={500} height={500} alt="" />
        </div>

        <div className='about-right'>
            <h3>Me And Choice CNC & 3D Craft</h3>
            <p>Hi Everyone my name is Bishnu Lal Tamang.A young Entrepreneur originally from Kavrepalanchok District, Panchkahl Municipality Ward NO. 13 Koshidekha.And i am runnig Woodworking,Custom Design and CNC work since 2023.I have been engaged in this business with 10 years of experience in South Korea.I have completed my 10 year of working tenure with hard work and honesty,during my working period i was not only working, i was learning CNC work simultaneously because i wanted to use my skill and the experieince in Nepal. So after i returned back to Nepal,i have decided to start this business. The name "Choice CNC & 3D Craft" is named with the aim of making customized wood products with the own choice of customer along with 3D craft. Located in the Imadol,Lalitpur of Kathmandu valley providing best CNC work sercive in the town.
            "I would like to request all the young Nepalese who are working in foreign country right now,work hard and complete your working tenure honestly, it does ot matter whatever work you are doing and wherever you are working along with your work learn and develop your skill & knowledge.Then come back to our beautiful country Nepal and help to grow the Nation by using your knowledge and experience."</p>
            <img src={bishnu} width={500} height={500} alt="" />
        </div>
        
        
    </div>
  )
}

export default About
